### ISSUE TITLE
Deploy windows updates from pulse server

### ISSUE THREAD

**Issue by botheis** [medulla-tech/medulla#168]
<a href="https://github.com/neoclust"><img src="https://avatars1.githubusercontent.com/u/285923?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [neoclust](https://github.com/neoclust)**
_Friday Dec 16, 2016 at 10:36 GMT_
_Originally opened as https://github.com/pulse-project/pulse/issues/59_

----

**Comment by neoclust** [comment]
this is now available with next medulla 4.7 release
