### ISSUE TITLE
apt cache updated failed gpg error

### ISSUE THREAD

**Issue by battilanah** [medulla-tech/medulla#493]
Bonjour,

quand j'essaie de lancer le playbook, tout fonctionne jusqu'à l'étape d'installer les paquets depuis apt.siveo.net/stable.list
le script affiche une erreur : les signatures suivantes n'ont pas pu etre verifiées car la clé publiqu n'est pas disponible : No_PUBKEY 20DF360B7BCADC9 le dépot https://apt.siveo.net stable inrelease n'est pas signé

y'a-t-il une remédiation? 

merci

**Comment by neoclust** [comment]
Comme vu ensemble sur discord, le ticket peut etre fermé car c'est géré par le nouveau script d'intallation
